/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel.management;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author shanilka
 */
public class UPDATEPACKAGE extends javax.swing.JFrame {

    /**
     * Creates new form UPDATEPACKAGE
     */
    public UPDATEPACKAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pkghome = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pkggolden = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gtxttour = new javax.swing.JTextField();
        gtxtplace = new javax.swing.JTextField();
        gtxtaccomadation = new javax.swing.JTextField();
        gtxttransfer = new javax.swing.JTextField();
        gtxtmean = new javax.swing.JTextField();
        gtxtcost = new javax.swing.JTextField();
        gtxtdetails = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        pkgsilver = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stxttour = new javax.swing.JTextField();
        stxtplace = new javax.swing.JTextField();
        stxtaccomadation = new javax.swing.JTextField();
        stxttransfer = new javax.swing.JTextField();
        stxtmean = new javax.swing.JTextField();
        stxtcost = new javax.swing.JTextField();
        stxtdetails = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        pkgbronze = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btxttour = new javax.swing.JTextField();
        btxtplace = new javax.swing.JTextField();
        btxtaccomadation = new javax.swing.JTextField();
        btxttransfer = new javax.swing.JTextField();
        btxtmean = new javax.swing.JTextField();
        btxtcost = new javax.swing.JTextField();
        btxtdetails = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 75));
        setPreferredSize(new java.awt.Dimension(800, 675));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 675));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE PACKAGE DETAILS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 636));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GOLDEN PACKAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SILVER PACKAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BRONZE PACKAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(728, 450));

        pkghome.setBackground(new java.awt.Color(200, 235, 255));
        pkghome.setPreferredSize(new java.awt.Dimension(728, 450));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel23.setText("UPDATE");

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel24.setText("PACKAGE DETAILS");

        javax.swing.GroupLayout pkghomeLayout = new javax.swing.GroupLayout(pkghome);
        pkghome.setLayout(pkghomeLayout);
        pkghomeLayout.setHorizontalGroup(
            pkghomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkghomeLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(pkghomeLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pkghomeLayout.setVerticalGroup(
            pkghomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkghomeLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pkggolden.setBackground(new java.awt.Color(200, 235, 255));
        pkggolden.setPreferredSize(new java.awt.Dimension(728, 450));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Tour Type");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Visit Places");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Accomadations");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Transfer Mode");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Mean Plans");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Cost Per Person");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Extra Details");

        gtxttour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxttourActionPerformed(evt);
            }
        });

        gtxtplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxtplaceActionPerformed(evt);
            }
        });

        gtxtaccomadation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxtaccomadationActionPerformed(evt);
            }
        });

        gtxttransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxttransferActionPerformed(evt);
            }
        });

        gtxtmean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxtmeanActionPerformed(evt);
            }
        });

        gtxtcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxtcostActionPerformed(evt);
            }
        });

        gtxtdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtxtdetailsActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pkggoldenLayout = new javax.swing.GroupLayout(pkggolden);
        pkggolden.setLayout(pkggoldenLayout);
        pkggoldenLayout.setHorizontalGroup(
            pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkggoldenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(pkggoldenLayout.createSequentialGroup()
                        .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pkggoldenLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gtxttour, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(gtxtplace)
                                    .addComponent(gtxtaccomadation)
                                    .addComponent(gtxttransfer)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkggoldenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gtxtcost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(gtxtmean, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gtxtdetails, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pkggoldenLayout.setVerticalGroup(
            pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkggoldenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gtxttour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gtxtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gtxtaccomadation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gtxttransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gtxtmean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gtxtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pkggoldenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gtxtdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(28, 28, 28))
        );

        pkgsilver.setBackground(new java.awt.Color(200, 235, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Tour Type");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Visit Places");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Accomadations");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Transfer Mode");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setText("Mean Plans");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setText("Cost Per Person");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setText("Extra Details");

        stxttour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxttourActionPerformed(evt);
            }
        });

        stxtplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtplaceActionPerformed(evt);
            }
        });

        stxtaccomadation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtaccomadationActionPerformed(evt);
            }
        });

        stxttransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxttransferActionPerformed(evt);
            }
        });

        stxtmean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtmeanActionPerformed(evt);
            }
        });

        stxtcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtcostActionPerformed(evt);
            }
        });

        stxtdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stxtdetailsActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SAVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pkgsilverLayout = new javax.swing.GroupLayout(pkgsilver);
        pkgsilver.setLayout(pkgsilverLayout);
        pkgsilverLayout.setHorizontalGroup(
            pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkgsilverLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(pkgsilverLayout.createSequentialGroup()
                        .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pkgsilverLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stxttour, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(stxtplace)
                                    .addComponent(stxtaccomadation)
                                    .addComponent(stxttransfer)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkgsilverLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stxtcost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(stxtmean, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stxtdetails, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pkgsilverLayout.setVerticalGroup(
            pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkgsilverLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stxttour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stxtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(stxtaccomadation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(stxttransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(stxtmean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(stxtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pkgsilverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(stxtdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(19, 19, 19))
        );

        pkgbronze.setBackground(new java.awt.Color(200, 235, 255));
        pkgbronze.setPreferredSize(new java.awt.Dimension(728, 450));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setText("Tour Type");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel17.setText("Visit Places");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setText("Accomadations");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setText("Transfer Mode");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel20.setText("Mean Plans");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setText("Cost Per Person");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel22.setText("Extra Details");

        btxttour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxttourActionPerformed(evt);
            }
        });

        btxtplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxtplaceActionPerformed(evt);
            }
        });

        btxtaccomadation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxtaccomadationActionPerformed(evt);
            }
        });

        btxttransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxttransferActionPerformed(evt);
            }
        });

        btxtmean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxtmeanActionPerformed(evt);
            }
        });

        btxtcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxtcostActionPerformed(evt);
            }
        });

        btxtdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxtdetailsActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pkgbronzeLayout = new javax.swing.GroupLayout(pkgbronze);
        pkgbronze.setLayout(pkgbronzeLayout);
        pkgbronzeLayout.setHorizontalGroup(
            pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkgbronzeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(pkgbronzeLayout.createSequentialGroup()
                        .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pkgbronzeLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btxttour, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(btxtplace)
                                    .addComponent(btxtaccomadation)
                                    .addComponent(btxttransfer)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkgbronzeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btxtcost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(btxtmean, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btxtdetails, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pkgbronzeLayout.setVerticalGroup(
            pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkgbronzeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btxttour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btxtplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(btxtaccomadation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(btxttransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btxtmean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btxtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pkgbronzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btxtdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pkgbronze, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkgsilver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkggolden, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkghome, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pkgbronze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkgsilver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkggolden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pkghome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gtxttourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxttourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxttourActionPerformed

    private void gtxtplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxtplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxtplaceActionPerformed

    private void gtxtaccomadationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxtaccomadationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxtaccomadationActionPerformed

    private void gtxttransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxttransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxttransferActionPerformed

    private void gtxtmeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxtmeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxtmeanActionPerformed

    private void gtxtcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxtcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxtcostActionPerformed

    private void gtxtdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtxtdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtxtdetailsActionPerformed

    private void stxttourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxttourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxttourActionPerformed

    private void stxtplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtplaceActionPerformed

    private void stxtaccomadationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtaccomadationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtaccomadationActionPerformed

    private void stxttransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxttransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxttransferActionPerformed

    private void stxtmeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtmeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtmeanActionPerformed

    private void stxtcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtcostActionPerformed

    private void stxtdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stxtdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stxtdetailsActionPerformed

    private void btxttourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxttourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxttourActionPerformed

    private void btxtplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxtplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxtplaceActionPerformed

    private void btxtaccomadationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxtaccomadationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxtaccomadationActionPerformed

    private void btxttransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxttransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxttransferActionPerformed

    private void btxtmeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxtmeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxtmeanActionPerformed

    private void btxtcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxtcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxtcostActionPerformed

    private void btxtdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxtdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxtdetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM packagedetails where Package_Name = 'GOLDEN' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String tour = rs.getString(2);
                String place = rs.getString(3);
                String accomadation = rs.getString(4);
                String transfer = rs.getString(5);
                String mean = rs.getString(6);
                String cost = rs.getString(8);
                String details = rs.getString(7);
                
                gtxttour.setText(tour);
                gtxtplace.setText(place);
                gtxtaccomadation.setText(accomadation);
                gtxttransfer.setText(transfer);
                gtxtmean.setText(mean);
                gtxtcost.setText(cost);
                gtxtdetails.setText(details);
                
               
                
            }
            
            
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        pkggolden.setVisible(true);
        pkghome.setVisible(false);
        pkgsilver.setVisible(false);
        pkgbronze.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM packagedetails where Package_Name = 'SILVER' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String tour = rs.getString(2);
                String place = rs.getString(3);
                String accomadation = rs.getString(4);
                String transfer = rs.getString(5);
                String mean = rs.getString(6);
                String cost = rs.getString(8);
                String details = rs.getString(7);
                
                stxttour.setText(tour);
                stxtplace.setText(place);
                stxtaccomadation.setText(accomadation);
                stxttransfer.setText(transfer);
                stxtmean.setText(mean);
                stxtcost.setText(cost);
                stxtdetails.setText(details);
                
               
                
            }
            
            
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        pkggolden.setVisible(false);
        pkghome.setVisible(false);
        pkgsilver.setVisible(true);
        pkgbronze.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM packagedetails where Package_Name = 'BRONZE' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String tour = rs.getString(2);
                String place = rs.getString(3);
                String accomadation = rs.getString(4);
                String transfer = rs.getString(5);
                String mean = rs.getString(6);
                String cost = rs.getString(8);
                String details = rs.getString(7);
                
                btxttour.setText(tour);
                btxtplace.setText(place);
                btxtaccomadation.setText(accomadation);
                btxttransfer.setText(transfer);
                btxtmean.setText(mean);
                btxtcost.setText(cost);
                btxtdetails.setText(details);
                
               
                
            }
            
            
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        pkggolden.setVisible(false);
        pkghome.setVisible(false);
        pkgsilver.setVisible(false);
        pkgbronze.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                String tour = gtxttour.getText();
                String place = gtxtplace.getText();
                String accomadation = gtxtaccomadation.getText();
                String transfer = gtxttransfer.getText();
                String mean = gtxtmean.getText();
                String cost = gtxtcost.getText();
                String details = gtxtdetails.getText();
        
           if(tour.trim().equals("") || place.trim().equals("") || accomadation.trim().equals("") ||
                 cost.trim().equals("") || transfer.trim().equals("") || mean.trim().equals("") || details.trim().equals(""))
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `packagedetails` SET `Tour_Type` = '"+tour+"', `Visit_Places` = '"+place+"', `Accomadations` = '"+ accomadation+"', `Transfer_Mode` = '"+transfer+"',`Mean_Plan` = '"+mean+"',"
                    + "`Extra_Details` = '"+details+"',"+ "`Cost` = '"+cost+"' WHERE `packagedetails`.`Package_Name` = 'GOLDEN'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String tour = stxttour.getText();
                String place = stxtplace.getText();
                String accomadation = stxtaccomadation.getText();
                String transfer = stxttransfer.getText();
                String mean = stxtmean.getText();
                String cost = stxtcost.getText();
                String details = stxtdetails.getText();
        
           if(tour.trim().equals("") || place.trim().equals("") || accomadation.trim().equals("") ||
                 cost.trim().equals("") || transfer.trim().equals("") || mean.trim().equals("") || details.trim().equals(""))
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `packagedetails` SET `Tour_Type` = '"+tour+"', `Visit_Places` = '"+place+"', `Accomadations` = '"+ accomadation+"', `Transfer_Mode` = '"+transfer+"',`Mean_Plan` = '"+mean+"',"
                    + "`Extra_Details` = '"+details+"',"+ "`Cost` = '"+cost+"' WHERE `packagedetails`.`Package_Name` = 'SILVER'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String tour = btxttour.getText();
                String place = btxtplace.getText();
                String accomadation = btxtaccomadation.getText();
                String transfer = btxttransfer.getText();
                String mean = btxtmean.getText();
                String cost = btxtcost.getText();
                String details = btxtdetails.getText();
        
           if(tour.trim().equals("") || place.trim().equals("") || accomadation.trim().equals("") ||
                 cost.trim().equals("") || transfer.trim().equals("") || mean.trim().equals("") || details.trim().equals(""))
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `packagedetails` SET `Tour_Type` = '"+tour+"', `Visit_Places` = '"+place+"', `Accomadations` = '"+ accomadation+"', `Transfer_Mode` = '"+transfer+"',`Mean_Plan` = '"+mean+"',"
                    + "`Extra_Details` = '"+details+"',"+ "`Cost` = '"+cost+"' WHERE `packagedetails`.`Package_Name` = 'BRONZE'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEPACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEPACKAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btxtaccomadation;
    private javax.swing.JTextField btxtcost;
    private javax.swing.JTextField btxtdetails;
    private javax.swing.JTextField btxtmean;
    private javax.swing.JTextField btxtplace;
    private javax.swing.JTextField btxttour;
    private javax.swing.JTextField btxttransfer;
    private javax.swing.JTextField gtxtaccomadation;
    private javax.swing.JTextField gtxtcost;
    private javax.swing.JTextField gtxtdetails;
    private javax.swing.JTextField gtxtmean;
    private javax.swing.JTextField gtxtplace;
    private javax.swing.JTextField gtxttour;
    private javax.swing.JTextField gtxttransfer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel pkgbronze;
    public javax.swing.JPanel pkggolden;
    public javax.swing.JPanel pkghome;
    public javax.swing.JPanel pkgsilver;
    private javax.swing.JTextField stxtaccomadation;
    private javax.swing.JTextField stxtcost;
    private javax.swing.JTextField stxtdetails;
    private javax.swing.JTextField stxtmean;
    private javax.swing.JTextField stxtplace;
    private javax.swing.JTextField stxttour;
    private javax.swing.JTextField stxttransfer;
    // End of variables declaration//GEN-END:variables
}
