/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel.management;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author shanilka
 */
public class UPDATEVEHICLE extends javax.swing.JFrame {

    /**
     * Creates new form UPDATEVEHICLE
     */
    public UPDATEVEHICLE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        motorbike = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        mtxt1 = new javax.swing.JTextField();
        mtxt2 = new javax.swing.JTextField();
        mtxt3 = new javax.swing.JTextField();
        mtxt4 = new javax.swing.JTextField();
        mtxt5 = new javax.swing.JTextField();
        mtxt6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        cars = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        ctxt1 = new javax.swing.JTextField();
        ctxt2 = new javax.swing.JTextField();
        ctxt3 = new javax.swing.JTextField();
        ctxt4 = new javax.swing.JTextField();
        ctxt5 = new javax.swing.JTextField();
        ctxt6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        vans = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        vtxt1 = new javax.swing.JTextField();
        vtxt2 = new javax.swing.JTextField();
        vtxt3 = new javax.swing.JTextField();
        vtxt4 = new javax.swing.JTextField();
        vtxt5 = new javax.swing.JTextField();
        vtxt6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        buses = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        btxt1 = new javax.swing.JTextField();
        btxt2 = new javax.swing.JTextField();
        btxt3 = new javax.swing.JTextField();
        btxt4 = new javax.swing.JTextField();
        btxt5 = new javax.swing.JTextField();
        btxt6 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        home1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE VEHICLES DETAILS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BUSES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MOTORCYCLES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VANS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CARS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(628, 340));
        jPanel4.setPreferredSize(new java.awt.Dimension(628, 345));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        motorbike.setBackground(new java.awt.Color(200, 234, 255));
        motorbike.setPreferredSize(new java.awt.Dimension(628, 345));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel91.setText("Rate Per Day");

        jLabel92.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel92.setText("Seating Capacity");

        jLabel93.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel93.setText("Fuel Type");

        jLabel94.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel94.setText("Seating Capacity");

        jLabel95.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel95.setText("Driver's Amount Per Day");

        jLabel96.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel96.setText("Extra");

        mtxt1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mtxt2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mtxt3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mtxt4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mtxt5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mtxt6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SAVE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout motorbikeLayout = new javax.swing.GroupLayout(motorbike);
        motorbike.setLayout(motorbikeLayout);
        motorbikeLayout.setHorizontalGroup(
            motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motorbikeLayout.createSequentialGroup()
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(motorbikeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addGroup(motorbikeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel94)
                            .addComponent(jLabel92)
                            .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mtxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mtxt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        motorbikeLayout.setVerticalGroup(
            motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motorbikeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(mtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(mtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel93)
                    .addComponent(mtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(mtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel95)
                    .addComponent(mtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(motorbikeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel96)
                    .addComponent(mtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(14, 14, 14))
        );

        jPanel4.add(motorbike, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 345));

        cars.setBackground(new java.awt.Color(200, 234, 255));
        cars.setPreferredSize(new java.awt.Dimension(628, 345));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel73.setText("Rate Per Day");

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel74.setText("Seating Capacity");

        jLabel75.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel75.setText("Fuel Type");

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel76.setText("Seating Capacity");

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel77.setText("Driver's Amount Per Day");

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel78.setText("Extra");

        ctxt1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ctxt2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ctxt3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ctxt4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ctxt5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        ctxt6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carsLayout = new javax.swing.GroupLayout(cars);
        cars.setLayout(carsLayout);
        carsLayout.setHorizontalGroup(
            carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carsLayout.createSequentialGroup()
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(carsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(carsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel76)
                            .addComponent(jLabel74)
                            .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        carsLayout.setVerticalGroup(
            carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(ctxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(ctxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(ctxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(ctxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(ctxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(carsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(ctxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(14, 14, 14))
        );

        jPanel4.add(cars, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 345));

        vans.setBackground(new java.awt.Color(200, 234, 255));
        vans.setPreferredSize(new java.awt.Dimension(628, 345));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel79.setText("Rate Per Day");

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel80.setText("Seating Capacity");

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel81.setText("Fuel Type");

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel82.setText("Seating Capacity");

        jLabel83.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel83.setText("Driver's Amount Per Day");

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel84.setText("Extra");

        vtxt1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        vtxt2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        vtxt3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        vtxt4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        vtxt5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        vtxt6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SAVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vansLayout = new javax.swing.GroupLayout(vans);
        vans.setLayout(vansLayout);
        vansLayout.setHorizontalGroup(
            vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vansLayout.createSequentialGroup()
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(vansLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(vansLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel82)
                            .addComponent(jLabel80)
                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vtxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vtxt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        vansLayout.setVerticalGroup(
            vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vansLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(vtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(vtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(vtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(vtxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(vtxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(vansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(vtxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(14, 14, 14))
        );

        jPanel4.add(vans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 345));

        buses.setBackground(new java.awt.Color(200, 234, 255));
        buses.setPreferredSize(new java.awt.Dimension(628, 345));

        jLabel85.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel85.setText("Rate Per Day");

        jLabel86.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel86.setText("Seating Capacity");

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel87.setText("Fuel Type");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel88.setText("Seating Capacity");

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel89.setText("Driver's Amount Per Day");

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel90.setText("Extra");

        btxt1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btxt2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btxt3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btxt4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btxt5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btxt6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busesLayout = new javax.swing.GroupLayout(buses);
        buses.setLayout(busesLayout);
        busesLayout.setHorizontalGroup(
            busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busesLayout.createSequentialGroup()
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(busesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8))
                    .addGroup(busesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88)
                            .addComponent(jLabel86)
                            .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        busesLayout.setVerticalGroup(
            busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(btxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(btxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(btxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(btxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(btxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(busesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(btxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(14, 14, 14))
        );

        jPanel4.add(buses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 345));

        home1.setBackground(new java.awt.Color(200, 234, 255));
        home1.setPreferredSize(new java.awt.Dimension(628, 345));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 34)); // NOI18N
        jLabel2.setText("UPDATE");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 34)); // NOI18N
        jLabel3.setText("VEHICLES DETAILS");

        javax.swing.GroupLayout home1Layout = new javax.swing.GroupLayout(home1);
        home1.setLayout(home1Layout);
        home1Layout.setHorizontalGroup(
            home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home1Layout.createSequentialGroup()
                .addGroup(home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(home1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        home1Layout.setVerticalGroup(
            home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel4.add(home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 345));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(51, 51, 51)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM vehiclesdetails where Vehicle_Type = 'MOTORCYCLES' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String vehicletype = rs.getString(1);
                String seat = rs.getString(2);
                String fuel = rs.getString(3);
                String rate = rs.getString(4);
                String driver = rs.getString(5);
                String extra = rs.getString(6);
                
                
                mtxt1.setText(vehicletype);
                mtxt2.setText(seat);
                mtxt3.setText(fuel);
                mtxt4.setText(rate);
                mtxt5.setText(driver);
                mtxt6.setText(extra);
            
                
               
                
            }
            
            
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        motorbike.setVisible(true);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM vehiclesdetails where Vehicle_Type = 'CARS' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String vehicletype = rs.getString(1);
                String seat = rs.getString(2);
                String fuel = rs.getString(3);
                String rate = rs.getString(4);
                String driver = rs.getString(5);
                String extra = rs.getString(6);
                
                
                ctxt1.setText(vehicletype);
                ctxt2.setText(seat);
                ctxt3.setText(fuel);
                ctxt4.setText(rate);
                ctxt5.setText(driver);
                ctxt6.setText(extra);
               
            }
            }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        
        motorbike.setVisible(false);
        cars.setVisible(true);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM vehiclesdetails where Vehicle_Type = 'VANS' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String vehicletype = rs.getString(1);
                String seat = rs.getString(2);
                String fuel = rs.getString(3);
                String rate = rs.getString(4);
                String driver = rs.getString(5);
                String extra = rs.getString(6);
                
                
                vtxt1.setText(vehicletype);
                vtxt2.setText(seat);
                vtxt3.setText(fuel);
                vtxt4.setText(rate);
                vtxt5.setText(driver);
                vtxt6.setText(extra);
            }
            
            
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        
        motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(true);
        buses.setVisible(false);
        home1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM vehiclesdetails where Vehicle_Type = 'BUSES' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String vehicletype = rs.getString(1);
                String seat = rs.getString(2);
                String fuel = rs.getString(3);
                String rate = rs.getString(4);
                String driver = rs.getString(5);
                String extra = rs.getString(6);
                
                
                btxt1.setText(vehicletype);
                btxt2.setText(seat);
                btxt3.setText(fuel);
                btxt4.setText(rate);
                btxt5.setText(driver);
                btxt6.setText(extra);
            
            }
             }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        
        motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(true);
        home1.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                String vehicletype = mtxt1.getText();
                String seat = mtxt2.getText();
                String fuel = mtxt3.getText();
                String rate = mtxt4.getText();
                String driver = mtxt5.getText();
                String extra = mtxt6.getText();
               
           if(vehicletype.trim().equals("") || seat.trim().equals("") || fuel.trim().equals("") ||
                 rate.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"Some Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `vehiclesdetails` SET `Vehicle_Type` = '"+vehicletype+"', `Seating_Capacity` = '"+seat+"', `Fuel_Type` = '"+ fuel+"', `Rate_Per_Day` = '"+rate+"',`Driver's_Amount` = '"+driver+"',"
                    + "`Extra` = '"+extra+"'  WHERE `vehiclesdetails`.`Vehicle_Type` = 'MOTORCYCLES'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
            }
          motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(true);
         }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String vehicletype = ctxt1.getText();
                String seat = ctxt2.getText();
                String fuel = ctxt3.getText();
                String rate = ctxt4.getText();
                String driver = ctxt5.getText();
                String extra = ctxt6.getText();
               
           if(vehicletype.trim().equals("") || seat.trim().equals("") || fuel.trim().equals("") ||
                 rate.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"Some Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `vehiclesdetails` SET `Vehicle_Type` = '"+vehicletype+"', `Seating_Capacity` = '"+seat+"', `Fuel_Type` = '"+ fuel+"', `Rate_Per_Day` = '"+rate+"',`Driver's_Amount` = '"+driver+"',"
                    + "`Extra` = '"+extra+"'  WHERE `vehiclesdetails`.`Vehicle_Type` = 'CARS'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
            }
          motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(true);
         }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String vehicletype = vtxt1.getText();
                String seat = vtxt2.getText();
                String fuel = vtxt3.getText();
                String rate = vtxt4.getText();
                String driver = vtxt5.getText();
                String extra = vtxt6.getText();
               
           if(vehicletype.trim().equals("") || seat.trim().equals("") || fuel.trim().equals("") ||
                 rate.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"Some Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `vehiclesdetails` SET `Vehicle_Type` = '"+vehicletype+"', `Seating_Capacity` = '"+seat+"', `Fuel_Type` = '"+ fuel+"', `Rate_Per_Day` = '"+rate+"',`Driver's_Amount` = '"+driver+"',"
                    + "`Extra` = '"+extra+"'  WHERE `vehiclesdetails`.`Vehicle_Type` = 'VANS'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
            }
          motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(true);
          
         }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String vehicletype = btxt1.getText();
                String seat = btxt2.getText();
                String fuel = btxt3.getText();
                String rate = btxt4.getText();
                String driver = btxt5.getText();
                String extra = btxt6.getText();
               
           if(vehicletype.trim().equals("") || seat.trim().equals("") || fuel.trim().equals("") ||
                 rate.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"Some Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `vehiclesdetails` SET `Vehicle_Type` = '"+vehicletype+"', `Seating_Capacity` = '"+seat+"', `Fuel_Type` = '"+ fuel+"', `Rate_Per_Day` = '"+rate+"',`Driver's_Amount` = '"+driver+"',"
                    + "`Extra` = '"+extra+"'  WHERE `vehiclesdetails`.`Vehicle_Type` = 'BUSES'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
            }
        motorbike.setVisible(false);
        cars.setVisible(false);
        vans.setVisible(false);
        buses.setVisible(false);
        home1.setVisible(true);
         }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEVEHICLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEVEHICLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEVEHICLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEVEHICLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEVEHICLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btxt1;
    private javax.swing.JTextField btxt2;
    private javax.swing.JTextField btxt3;
    private javax.swing.JTextField btxt4;
    private javax.swing.JTextField btxt5;
    private javax.swing.JTextField btxt6;
    public javax.swing.JPanel buses;
    public javax.swing.JPanel cars;
    private javax.swing.JTextField ctxt1;
    private javax.swing.JTextField ctxt2;
    private javax.swing.JTextField ctxt3;
    private javax.swing.JTextField ctxt4;
    private javax.swing.JTextField ctxt5;
    private javax.swing.JTextField ctxt6;
    public javax.swing.JPanel home1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel motorbike;
    private javax.swing.JTextField mtxt1;
    private javax.swing.JTextField mtxt2;
    private javax.swing.JTextField mtxt3;
    private javax.swing.JTextField mtxt4;
    private javax.swing.JTextField mtxt5;
    private javax.swing.JTextField mtxt6;
    public javax.swing.JPanel vans;
    private javax.swing.JTextField vtxt1;
    private javax.swing.JTextField vtxt2;
    private javax.swing.JTextField vtxt3;
    private javax.swing.JTextField vtxt4;
    private javax.swing.JTextField vtxt5;
    private javax.swing.JTextField vtxt6;
    // End of variables declaration//GEN-END:variables
}
