/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel.management;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author shanilka
 */
public class UPDATEHOTELPRICES extends javax.swing.JFrame {

    /**
     * Creates new form UPDATEHOTELPRICES
     */
    public UPDATEHOTELPRICES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        hotel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        h1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        h1txt1 = new javax.swing.JTextField();
        h1txt2 = new javax.swing.JTextField();
        h1txt3 = new javax.swing.JTextField();
        h1txt4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        h2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        h2txt1 = new javax.swing.JTextField();
        h2txt2 = new javax.swing.JTextField();
        h2txt3 = new javax.swing.JTextField();
        h2txt4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        h3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        h3txt1 = new javax.swing.JTextField();
        h3txt2 = new javax.swing.JTextField();
        h3txt3 = new javax.swing.JTextField();
        h3txt4 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        h4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        h4txt1 = new javax.swing.JTextField();
        h4txt2 = new javax.swing.JTextField();
        h4txt3 = new javax.swing.JTextField();
        h4txt4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        h5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        h5txt1 = new javax.swing.JTextField();
        h5txt2 = new javax.swing.JTextField();
        h5txt3 = new javax.swing.JTextField();
        h5txt4 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        h6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        h6txt1 = new javax.swing.JTextField();
        h6txt2 = new javax.swing.JTextField();
        h6txt3 = new javax.swing.JTextField();
        h6txt4 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(845, 550));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE HOTEL DETAILS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/Kingsbury.jpg"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/chaaya-citadel-hotel-exterior.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("UPDATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/113-light-house-galle-08.jpg"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/Palm-stone-retreat-main-building1.jpg"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/Anantara Peace Heaven.jpg"))); // NOI18N
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/management/Kandalama.jpg"))); // NOI18N
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        hotel.setBackground(new java.awt.Color(200, 235, 255));
        hotel.setPreferredSize(new java.awt.Dimension(483, 438));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Hotel Details");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setText("Update");

        javax.swing.GroupLayout hotelLayout = new javax.swing.GroupLayout(hotel);
        hotel.setLayout(hotelLayout);
        hotelLayout.setHorizontalGroup(
            hotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelLayout.createSequentialGroup()
                .addGroup(hotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hotelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        hotelLayout.setVerticalGroup(
            hotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        h1.setBackground(new java.awt.Color(200, 235, 255));
        h1.setPreferredSize(new java.awt.Dimension(483, 438));
        h1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Hotel Name");
        h1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Hotel Type");
        h1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Location");
        h1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Cost Per Person For One Day");
        h1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h1txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h1.add(h1txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h1txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h1.add(h1txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h1txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h1.add(h1txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h1txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h1.add(h1txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        h1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        h2.setBackground(new java.awt.Color(200, 235, 255));
        h2.setPreferredSize(new java.awt.Dimension(483, 438));
        h2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Hotel Name");
        h2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Hotel Type");
        h2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Location");
        h2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Cost Per Person For One Day");
        h2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h2txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h2.add(h2txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h2txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h2.add(h2txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h2txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h2.add(h2txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h2txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h2.add(h2txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SAVE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        h2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        h3.setBackground(new java.awt.Color(200, 235, 255));
        h3.setPreferredSize(new java.awt.Dimension(483, 438));
        h3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Hotel Name");
        h3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Hotel Type");
        h3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Location");
        h3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Cost Per Person For One Day");
        h3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h3txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h3.add(h3txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h3txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h3.add(h3txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h3txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h3.add(h3txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h3txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h3.add(h3txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("SAVE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        h3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        h4.setBackground(new java.awt.Color(200, 235, 255));
        h4.setPreferredSize(new java.awt.Dimension(483, 438));
        h4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Hotel Name");
        h4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Hotel Type");
        h4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Location");
        h4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Cost Per Person For One Day");
        h4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h4txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h4.add(h4txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h4txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h4.add(h4txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h4txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h4.add(h4txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h4txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h4.add(h4txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("SAVE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        h4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        h5.setBackground(new java.awt.Color(200, 235, 255));
        h5.setPreferredSize(new java.awt.Dimension(483, 438));
        h5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Hotel Name");
        h5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Hotel Type");
        h5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Location");
        h5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Cost Per Person For One Day");
        h5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h5txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h5.add(h5txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h5txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h5.add(h5txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h5txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h5.add(h5txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h5txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h5.add(h5txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("SAVE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        h5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        h6.setBackground(new java.awt.Color(200, 235, 255));
        h6.setPreferredSize(new java.awt.Dimension(483, 438));
        h6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Hotel Name");
        h6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 80, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Hotel Type");
        h6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 144, 80, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Location");
        h6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 222, 80, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Cost Per Person For One Day");
        h6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 307, 196, -1));

        h6txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h6.add(h6txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 71, 278, -1));

        h6txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h6.add(h6txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 141, 278, -1));

        h6txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h6.add(h6txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 219, 278, -1));

        h6txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        h6.add(h6txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 304, 189, -1));

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("SAVE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        h6.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(h4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(h3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(h4, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(h5, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addComponent(h3, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addComponent(h2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addComponent(h6, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(hotel, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '1' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h1txt1.setText(hotelname);
                h1txt2.setText(hoteltype);
                h1txt3.setText(location);
                h1txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        h1.setVisible(true);
        h2.setVisible(false);
        h3.setVisible(false);
        h4.setVisible(false);
        h5.setVisible(false);
        h6.setVisible(false);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '5' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h2txt1.setText(hotelname);
                h2txt2.setText(hoteltype);
                h2txt3.setText(location);
                h2txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        
        h2.setVisible(true);
        h1.setVisible(false);
        h3.setVisible(false);
        h4.setVisible(false);
        h5.setVisible(false);
        h6.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '3' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h3txt1.setText(hotelname);
                h3txt2.setText(hoteltype);
                h3txt3.setText(location);
                h3txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        h3.setVisible(true);
        h2.setVisible(false);
        h1.setVisible(false);
        h4.setVisible(false);
        h5.setVisible(false);
        h6.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '6' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h4txt1.setText(hotelname);
                h4txt2.setText(hoteltype);
                h4txt3.setText(location);
                h4txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        h4.setVisible(true);
        h2.setVisible(false);
        h3.setVisible(false);
        h1.setVisible(false);
        h5.setVisible(false);
        h6.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '4' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h5txt1.setText(hotelname);
                h5txt2.setText(hoteltype);
                h5txt3.setText(location);
                h5txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        h5.setVisible(true);
        h2.setVisible(false);
        h3.setVisible(false);
        h4.setVisible(false);
        h1.setVisible(false);
        h6.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
              
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
                con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "SELECT * FROM hoteldetails where ID = '2' ";
           PreparedStatement st;
                st = (PreparedStatement)con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                String hotelname = rs.getString(2);
                String hoteltype = rs.getString(3);
                String location = rs.getString(4);
                String cost = rs.getString(5);
                
                h6txt1.setText(hotelname);
                h6txt2.setText(hoteltype);
                h6txt3.setText(location);
                h6txt4.setText(cost);
                
               
                
            }else{
                
                JOptionPane.showMessageDialog(this,"Update Successfully");
            }
            
            
             }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }        
        
        
        h6.setVisible(true);
        h2.setVisible(false);
        h3.setVisible(false);
        h4.setVisible(false);
        h5.setVisible(false);
        h1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String hotelname = h1txt1.getText();
        String hoteltype = h1txt2.getText();
        String location = h1txt3.getText();
        String cost = h1txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '1'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String hotelname = h2txt1.getText();
        String hoteltype = h2txt2.getText();
        String location = h2txt3.getText();
        String cost = h2txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '5'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String hotelname = h3txt1.getText();
        String hoteltype = h3txt2.getText();
        String location = h3txt3.getText();
        String cost = h3txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '3'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String hotelname = h4txt1.getText();
        String hoteltype = h4txt2.getText();
        String location = h4txt3.getText();
        String cost = h4txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '6'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       String hotelname = h5txt1.getText();
        String hoteltype = h5txt2.getText();
        String location = h5txt3.getText();
        String cost = h5txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '4'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String hotelname = h6txt1.getText();
        String hoteltype = h6txt2.getText();
        String location = h6txt3.getText();
        String cost = h6txt4.getText();
        
       
        
        if(hotelname.trim().equals("") || hoteltype.trim().equals("") || location.trim().equals("") ||
                 cost.trim().equals("") )
            {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
           
        }
        
        else{
            
          
          try {
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/travel_management", "root","");
            String sql = "UPDATE `hoteldetails` SET `Hotel_Name` = '"+hotelname+"', `Hotel_Type` = '"+hoteltype+"', `location` = '"+ location+"', `cost` = '"+cost+"' WHERE `hoteldetails`.`ID` = '2'" ;
           
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Successfully");   
            con.close();
            
            }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this,e);
        }
          
         
            
            }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATEHOTELPRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATEHOTELPRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATEHOTELPRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATEHOTELPRICES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEHOTELPRICES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel h1;
    private javax.swing.JTextField h1txt1;
    private javax.swing.JTextField h1txt2;
    private javax.swing.JTextField h1txt3;
    private javax.swing.JTextField h1txt4;
    public javax.swing.JPanel h2;
    private javax.swing.JTextField h2txt1;
    private javax.swing.JTextField h2txt2;
    private javax.swing.JTextField h2txt3;
    private javax.swing.JTextField h2txt4;
    public javax.swing.JPanel h3;
    private javax.swing.JTextField h3txt1;
    private javax.swing.JTextField h3txt2;
    private javax.swing.JTextField h3txt3;
    private javax.swing.JTextField h3txt4;
    public javax.swing.JPanel h4;
    private javax.swing.JTextField h4txt1;
    private javax.swing.JTextField h4txt2;
    private javax.swing.JTextField h4txt3;
    private javax.swing.JTextField h4txt4;
    public javax.swing.JPanel h5;
    private javax.swing.JTextField h5txt1;
    private javax.swing.JTextField h5txt2;
    private javax.swing.JTextField h5txt3;
    private javax.swing.JTextField h5txt4;
    public javax.swing.JPanel h6;
    private javax.swing.JTextField h6txt1;
    private javax.swing.JTextField h6txt2;
    private javax.swing.JTextField h6txt3;
    private javax.swing.JTextField h6txt4;
    public javax.swing.JPanel hotel;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
